# Generated by Django 5.2.1 on 2025-05-25 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_appointment_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Imagerie', 'Imagerie'), ('Diagnostic', 'Diagnostic'), ('Chirurgie', 'Chirurgie'), ('Urgence', 'Urgence'), ('Monitoring', 'Monitoring')], max_length=20)),
                ('status', models.CharField(choices=[('Opérationnel', 'Opérationnel'), ('En maintenance', 'En maintenance'), ('Hors service', 'Hors service')], default='Opérationnel', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(choices=[('Consultation', 'Consultation'), ('Opération', 'Opération'), ('Urgence', 'Urgence'), ('Radiologie', 'Radiologie'), ('Laboratoire', 'Laboratoire')], max_length=20)),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Occupée', 'Occupée'), ('En maintenance', 'En maintenance')], default='Disponible', max_length=20)),
                ('capacite', models.IntegerField()),
                ('equipements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('medecin', 'Médecin'), ('pharmacien', 'Pharmacien'), ('admin', 'Administrateur')], max_length=20),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Préventive', 'Préventive'), ('Corrective', 'Corrective'), ('Inspection', 'Inspection'), ('Calibration', 'Calibration')], max_length=20)),
                ('status', models.CharField(choices=[('Planifiée', 'Planifiée'), ('En cours', 'En cours'), ('Terminée', 'Terminée')], default='Planifiée', max_length=20)),
                ('description', models.TextField()),
                ('date_prevue', models.DateField()),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.room'),
        ),
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('motif', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
    ]
